# Generated by Django 3.0.7 on 2020-06-27 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_end_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_request_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_start_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
